name: Waka Readme

on:
  schedule:
    - cron: "0 17 * * *" # runs at every 12AM UTC
  workflow_dispatch: # for manual workflow trigger
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: False
          SHOW_TIMEZONE: False
          SHOW_PROFILE_VIEWS: False
          SHOW_LOC_CHART: False
          SYMBOL_VERSION: 2
          COMMIT_BY_ME: True
